[package]
name = "saintnosub-bot"
version = "0.1.0"
authors = ["Lemiort <lemiort@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
telegram-bot = {git="https://github.com/telegram-rs/telegram-bot"}
tokio-core = "0.1"
tokio = { version = "0.2", features = ["full"] }
rawr = {git="https://github.com/Jokler/rawr.git"}